# Generated by Django 2.0.5 on 2018-06-06 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0003_auto_20180531_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='sir_name',
            new_name='sur_name',
        ),
    ]
